language: ruby
rvm:
- 2.1.1
env:
  matrix:
    secure: O6slEE86RuGbNuMZ7FzjCSH1zclM9JfBMMBjXz91DAdQJEw/2HijA75FxD0DS1bOLkt4g2NKc2GyOflBvl4mjAHTJw8vi+WCXeN367EkYxPg7UBsG5Sp5mq5pIyazpja80q0Ky4qeqbhO6e0tr9JGPuzk34iFncjkGBjzCpGGks=
addons:
  postgresql: "9.3"
  code_climate:
    repo_token: 2dde6314fbf4cf42323935dd32da821f8f283f8e60b5d6a66241d5261a0f0fec
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate
notifications:
  slack: cyrusinnovation:t1h6NsX1mSI72ryir6kOvLiv
